### PR TITLE
Uto1 init

### PR DESCRIPTION
**Pull request by PawelGorny**
new agent, new lib for hands evaluation

### CODE REVIEW

**Comment by dickreuter** [comment]
Thanks for your contribution, looks great. 

Just wondering if we could make deuce part of the python environment (in requirements.txt) rather than have a copy of it in this repo. Unless it was necessary to make changes to it?

**Comment by PawelGorny** [comment]
> Just wondering if we could make deuce part of the python environment (in requirements.txt) rather than have a copy of it in this repo. Unless it was necessary to make changes to it?

Ufortunately yes, I had to do some minor changes for python3.

**Comment by dickreuter** [comment]
There are a few pylint errors: https://travis-ci.com/dickreuter/neuron_poker/builds/127063657

can you add #pylint: skip-file at the top of the third party files so we don't need to apply pylint onto them. For your own files would be great if you could fix them.

**Comment by PawelGorny** [comment]
I have fixed the code style issues, but Travis complains about the log (output) size:
The job exceeded the maximum log length, and has been terminated.

**Pull request closed without merging**
