### PR TITLE
Fixed loading dqn agent

### PR DESCRIPTION
**Pull request by vkresch**
Resolves [this issue](https://github.com/dickreuter/neuron_poker/issues/16).

- To be able to load the agent one also needs to load the architecture not only the weights. I changed how to play the agent in the same way as we train the agent. 
- I also changed the Adam optimizer to tensorflow optimizer `tf.optimizers.Adam` since the keras `Adam` threw errors on my machine
- added also the line `tf.compat.v1.disable_eager_execution()` since it also threw me an error without it
- also changed `min_bet_equity=-.5` -> `min_bet_equity=.5` without the minus not sure if it was intentional

Nice project btw. Pls review my changes :)

### CODE REVIEW

**Comment by dickreuter** [comment]
Thanks for your contribution, looks great. Can you please have a look at tye pylint errors. Once they are fixed I'll have a closer look. You can either run the pylint test on your local machine (test_pylint.py) or see the errors listed in the travis build above. Let me know if you need more help.

**Comment by vkresch** [comment]
@dickreuter sure I am unable to fix this `gym_env/env.py:251:0: E1126: Sequence index is not an int, slice, or instance with __index__ (invalid-sequence-index)`. Not sure what to do I didn't even modify that file for my PR.

**Comment by dickreuter** [comment]
If it’s a false positive just put this at the end of the line or in the line above:
# pylint: disable= invalid-sequence-index

**Comment by vkresch** [comment]
@dickreuter can't see what's wrong now :(

**Comment by dickreuter** [comment]
Looks good to me. I think the problem is that travis outputs a large number of empty log lines and it then exceeds the 4MB limit. Not sure how to solve that. I will just merge it anyway for now.

**Pull request merged**
